* CompStats cheatsheet
Cheatsheet for the course /Computational Statistics (Spring 2022)/ read by N. Meinshausen.

This if a fork of [[https://github.com/RomeoV/comp-stats-cheat-sheet][this cheatsheet]].

*If you find any errors or you want to improve something, feel free to open a Pull Request.*

** Building with Overleaf

I used the GitHub integration provided by [[overleaf.com]][Overleaf]] to import this repository
into an Overleaf project. Overleaf then takes care of everything you need and you can
compile the document easily without needing to install anything locally.

** Local build instructions 
In case you want to compile locally, here are the instructions provided by [[https://github.com/RomeoV/][RomeoV]].

Although a pdf file is provided, you can build the pdf yourself.
You need to have a distribution of ~Latex~ aswell as the command-line tool ~minted~ installed (~pip install minted~). Then, clone the repository and the submodule and build it:
#+BEGIN_SRC
$ pdflatex --version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021/Arch Linux) [...]
$ pygmentize -V
Pygments version 2.9.0 [...]
$ git clone --recursive git@github.com:RomeoV/comp-stats-cheat-sheet.git
$ pdflatex -shell-escape formulary.tex
#+END_SRC
Sometimes the first run of ~pdflatex~ fails with error ~LaTeX Error: Can be used only in preamble.~
Cancel the compilation (with =X<Enter>=) and rerun the command.
